### ISSUE TITLE
line 14

### ISSUE THREAD

**Issue by Woah0420** [Eruptsy/C-Headers#1]
void*   (*set_file)(sk, sk);
The second argument 'sk' is invalid and using function pointers like this is retarded. Change the second 'sk' to 'char *'. And stop using function pointers if you don't know how! And you aren't returning the correct data type on line 37. Multiple possible memory leaks in lines 40 - 59. Line 12 & 13 there is no point of having a double pointer like that because you aren't using them correctly & there is a possible buffer over flow with them as well. Lines 61 - 68 you are returning something that is going to get poped out of the stack as soon as the scope ends. These are not all the issues but this is most.

**Comment by Woah0420** [comment]
not line 14 my bad (all the code)

**Comment by Eruptsy** [comment]
This was put out as a 'working' C lib. If you want to create a fork and contribute to it. that'll fine but this is set as it is

**Comment by Woah0420** [comment]
L
